### ISSUE TITLE
Migrate Coinbase API to use web endpoints

### ISSUE THREAD

**Issue by mattrasto** [ayushkumar0630/CoinArbitrage#6]
The Coinbase Python API package doesn't support Python 3.6 and has dangerous undocumented default behaviors (eg. specifying a coin pairing that doesn't exist defaults to USD/BTC or EUR/BTC). We should use the web API (https://developers.coinbase.com/api/v2) to avoid these issues.

**Comment by MatthewR3** [comment]
Update: there exists an unofficial Python 3 library (https://github.com/resy/coinbase_python3) but the move to using web endpoints reduces the possibility of having to maintain OOD code.
